runtime: python
env: flex
service: default
entrypoint: python mnca.py


runtime_config:
  python_version: 3

health_check:
  enable_health_check: False

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5


#[START env]
env_variables:
  DEBUG: True
#[END env]


