runtime: python
env: flex
service: default
entrypoint: python mnca.py


runtime_config:
  python_version: 3

health_check:
  enable_health_check: False

resources:
  cpu: 1
  memory_gb: 1.0


#[START env]
env_variables:
  DEBUG: True
#[END env]


